### ISSUE TITLE
[US-1-1] Administrators must be able to edit and remove course offerings for a semester

### ISSUE THREAD

**Issue by AntonNiko** [SENG499-S22-Company3/algorithm-1#10]
**Given** the administrator has access to the list of course offerings for a given semester, **When** the administrator edits details about the course offering (e.g. schedule, hours, dates...) and submits changes, **Then** the changes are persisted in the system and the update course offering is visible to the administrator.

**Comment by BrodyGimson** [comment]
Frontend related story. Closing issue
