### ISSUE TITLE
[US-1-2] Administrators must be able to trigger an automatic assignment of timeslots to courses

### ISSUE THREAD

**Issue by AntonNiko** [SENG499-S22-Company3/algorithm-1#11]
**Given** the administrator has provided the required input data, hard constraints, and soft constraints to the scheduling system, **When** the administrator requests an assignment of timeslots to courses, **Then** they will receive (within reasonable performance timeframes) a response from the system indicating that a new assignment was generated and that it is available for viewing.

**Comment by BrodyGimson** [comment]
**Hard Constraints:**
- A course cannot be scheduled before 8:30am or after 10:00pm
- Required courses, as determined by the program stream, cannot be scheduled during the same time slot
- Assignment does not conflict with other courses the assigned Professor is teaching
- Course are taught in blocks of 50 min, 80 min, or 3 hours
- Courses are offered on MTW, TH, or once per week
