### ISSUE TITLE
[ST-4-1] Create Github Actions pipeline building and testing Application

### ISSUE THREAD

**Issue by AntonNiko** [SENG499-S22-Company3/algorithm-1#54]

**Comment by BrodyGimson** [comment]
@AntonNiko GitHub actions complete, did we want to make a subtask for deployment?

**Comment by AntonNiko** [comment]
Yeah let's do it, I'm out right now but will do it when home. Will put up my HTTP server PR then do the deployment task.

**Comment by BrodyGimson** [comment]
I will make the subtask the close this issue
