### ISSUE TITLE
[ST-1-1-2] List of maps for different time slots to avoid required courses from conflicting

### ISSUE THREAD

**Issue by treavorgagne** [SENG499-S22-Company3/algorithm-1#89]
- [x] Create list of maps object to help with assignment creation and testing against hard requirements. Maps in the list correspond to a day, within the map keys are the timeslot, and values are the course subject and number in a string (i.e. "CSC115").

**Comment by BrodyGimson** [comment]
Initial struct for the timeslots is up on the branch "add-timeslot-map". If all looks good a pull request will be made to merge the branch into main.

**Comment by BrodyGimson** [comment]
PR created to merge with main.
