### ISSUE TITLE
[US-1-1] Assign Courses to Timeslots that Satisfy Hard Requirements

### ISSUE THREAD

**Issue by BrodyGimson** [SENG499-S22-Company3/algorithm-1#90]
**Hard Requirements:**
- [x] Check a course has not been scheduled before 8:30am or after 10:00pm
- [x] Check required courses, as determined by the program stream, have not been scheduled during the same time slot
- [x] Check courses are taught in blocks of 50 min, 80 min, or 3 hours - Refer to [ST-1-1-1] for more info
- [x] Check courses are offered on MTW, TH, or once per week - Refer to [ST-1-1-1] for more info

**Comment by nathantutak** [comment]
Need to ensure that courses remain in the same length of timeslot that they were in the past (ie 50 min course vs 80 min course)

**Comment by BrodyGimson** [comment]
Base map structures will make it not possible to add courses outside of university time and courses with same stream sequence.

**Comment by BrodyGimson** [comment]
Base schedule functions created now. Need to get methods created for initial schedule.

**Comment by BrodyGimson** [comment]
Methods for getting initial schedules has been created. 3 hour blocks won't be made in the random selection and is currently not implemented in the base timeslot map creation
